sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
jobs:
  include:
    - stage: futboljs
      script:
        - npm run fetch-spreadsheet
        - npm run build-prod
        - npm run build-manifest
      env: REACT_APP_COVERS_WORKSHEET_ID='oxkmli1' REACT_APP_CURIOSITIES_WORKSHEET_ID='oeu2u4b' REACT_APP_INSTANCE_NAME='futboljs' REACT_APP_POSITIONS_WORKSHEET_ID='oce51o4' REACT_APP_SHIRTS_WORKSHEET_ID='o4fh6yk' REACT_APP_SPREADSHEET_ID='10IreaMeMXPPrvx4bFuqU7eOjcAp7VCVP96c4jxs1Hk8' REACT_APP_DESCRIPTION='Estadísticas del fútbol.js.' REACT_APP_SOCIAL_IMAGE='https://futboljs.now.sh/assets/images/social-martes.jpg' REACT_APP_TITLE='Fútbol.js' REACT_APP_URL='https://futboljs.now.sh/'
    - stage: futbolmixto
      script:
        - npm run fetch-spreadsheet
        - npm run build-prod
        - npm run build-manifest
      env: REACT_APP_COVERS_WORKSHEET_ID='obpp9hl' REACT_APP_CURIOSITIES_WORKSHEET_ID='ooxq4mi' REACT_APP_INSTANCE_NAME='futbolmixto' REACT_APP_POSITIONS_WORKSHEET_ID='oce51o4' REACT_APP_SPREADSHEET_ID='1W5ihCnbzRV3UHa9lMCcJNOtFKWHVUI_0P5SKcdF4wig' REACT_APP_DESCRIPTION='Estadísticas del fútbol mixto.' REACT_APP_SOCIAL_IMAGE='https://futbolmixto.now.sh/assets/images/social-mixto.jpg' REACT_APP_TITLE='Fútbol Mixto' REACT_APP_URL='https://futbolmixto.now.sh/'
env:
  global:
    secure: P7U7K7gQrP9iwhrK5/paF2M0weqeD17Qg80/R9KQdNE8XnbSDutFDf5BiKiKRSu/n11LFxgf9xlJbI6IIc2KllXiCbt+805c1tcLD9zuy+ISYRYmoA7MZeSqXIvyqSfZ3nzoTNzN8IjxluRdxXk63zD0VWXTWZDHodibLP/xtfPxeY+sr5Q1CZ6SxNLb9Bp/rJbcUsZGnn+wUss6pJ8r/Q1b3EkkNi22RIB5EVeePGv8Fq8t/qCqB5nu4AMcEa7uyzmpNcr+59f7079CD/ydxHR9Q9o9ClfWdwkGm2FcLiWUq39NP4vBFWtXA7UroAWDk86n9mdNg1fsUVOlIoNsdiUpSGNVxh76snXUCbEFUm3J/l6rFjr7g+GRrFOje5L77dyJGgqCSaf5xM3ln9w3K2OkX9ejszql/rJNDZj/Xg7Nc8Boom08s5gGvuTqbyJXjYn/lznpbDaJQS7NHU84MfHx5RbXeLgyNL0v091WguPAev7AJICcROAB9iWMNWlQIN6XojxeqizK3/YagQDcdnvX1PfXB9kGbv2+Y0aU6bYiVtGhG+w3xm8m25J7QtWVaVq8uhldu6ASAHMF+E67CNOuo0ky/Nz49D1gLu5AiKVUVNaa2wUj3iGA4Knxj0PSndrGwWjEdt1WSPdBcdraTOI4xF73xWPt5VevYjRy/MU=