sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
script:
  - npm run generate-dataset
  - npm run generate-manifest
  - npm run build-prod
before_deploy:
  - npm i now --no-save
deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
  on:
    branch: master
after_deploy:
  - npm run scale
  - npm run clean-deploys
env:
  matrix:
    - REACT_APP_COVERS_WORKSHEET_ID='oxkmli1' REACT_APP_CURIOSITIES_WORKSHEET_ID='oeu2u4b' REACT_APP_INSTANCE_NAME='futboljs' REACT_APP_POSITIONS_WORKSHEETS_IDS='of1a6hw,o4afjjl,oobuyor,oba7wbv' REACT_APP_SHIRTS_WORKSHEET_ID='o4fh6yk' REACT_APP_SPREADSHEET_ID='1TihaiB5jc4guXKSIqplhdudunmyQivYQHuFooxzhHAE' REACT_APP_USERS_WORKSHEET_ID='oocerqf' REACT_APP_DESCRIPTION='Estadísticas del fútbol.js.' REACT_APP_SOCIAL_IMAGE='https://futboljs.now.sh/assets/images/social-martes.jpg' REACT_APP_TITLE='Fútbol.js' REACT_APP_URL='https://futboljs.now.sh/'
    - REACT_APP_COVERS_WORKSHEET_ID='oxkmli1' REACT_APP_CURIOSITIES_WORKSHEET_ID='oeu2u4b' REACT_APP_INSTANCE_NAME='futbolmixto' REACT_APP_POSITIONS_WORKSHEETS_IDS='of1a6hw' REACT_APP_SPREADSHEET_ID='1G4GJbURgjRs0GiAtWphVcVPNMgpvd0QdF_NMEZj5iSo' REACT_APP_USERS_WORKSHEET_ID='oocerqf' REACT_APP_DESCRIPTION='Estadísticas del fútbol mixto.' REACT_APP_SOCIAL_IMAGE='https://futbolmixto.now.sh/assets/images/social-mixto.jpg' REACT_APP_TITLE='Fútbol Mixto' REACT_APP_URL='https://futbolmixto.now.sh/'
